services:

  postgres:
    image: postgres:16
    container_name: lupito_postgres
    environment:
      POSTGRES_DB: lupitov1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - lupito_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: lupito_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lupito.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  lupito_pgdata:
