spring.datasource.url=jdbc:h2:mem:lupito_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true

spring.flyway.enabled=false

jwt.secret=test-secret-apenas-para-testes-unitarios
groq.api.key=test-key

# Desabilita o auto-configure de e-mail nos testes
spring.mail.username=test@lupito.dev
spring.mail.password=test
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
