# Configuracoes de producao
# Preencher via variaveis de ambiente em producao

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.flyway.placeholder-replacement=false

jwt.secret=${JWT_SECRET}

groq.api.key=${GROQ_API_KEY:}

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
