spring.datasource.url=jdbc:postgresql://localhost:5432/lupitov1
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.placeholder-replacement=false

jwt.secret=lupito-dev-secret-local-apenas-desenvolvimento
groq.api.key=${GROQ_API_KEY:}


spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}


spring.config.import=optional:classpath:application-local.properties
