-- ==========================================
-- Script para popular as trilhas e módulos
-- ==========================================

INSERT INTO tb_courses (title, description) VALUES ('Lógica de Programação', 'Aprenda os fundamentos da lógica de programação e algoritmos essenciais.');
INSERT INTO tb_courses (title, description) VALUES ('Desenvolvimento Web Básico', 'Domine as páginas web com as bases de HTML, CSS e JavaScript.');

INSERT INTO tb_sections (title, list_order, course_id) VALUES ('Módulos de Lógica', 1, 1);
INSERT INTO tb_sections (title, list_order, course_id) VALUES ('Módulos de Web', 1, 2);

INSERT INTO tb_lessons (title, theory_content, list_order, section_id) VALUES ('Introdução', 'Conteúdo do módulo: Introdução.', 1, 1);
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 1: O que define melhor os conceitos de Introdução?', 0, 1);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (1, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (1, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (1, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (1, 'Serve para ignorar erros');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 2: O que define melhor os conceitos de Introdução?', 0, 1);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (2, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (2, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (2, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (2, 'Serve para ignorar erros');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 3: O que define melhor os conceitos de Introdução?', 0, 1);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (3, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (3, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (3, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (3, 'Serve para ignorar erros');
INSERT INTO tb_lessons (title, theory_content, list_order, section_id) VALUES ('Variáveis', 'Conteúdo do módulo: Variáveis.', 2, 1);
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 1: O que define melhor os conceitos de Variáveis?', 0, 2);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (4, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (4, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (4, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (4, 'Serve para ignorar erros');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 2: O que define melhor os conceitos de Variáveis?', 0, 2);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (5, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (5, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (5, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (5, 'Serve para ignorar erros');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 3: O que define melhor os conceitos de Variáveis?', 0, 2);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (6, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (6, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (6, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (6, 'Serve para ignorar erros');
INSERT INTO tb_lessons (title, theory_content, list_order, section_id) VALUES ('Tipos de Dados', 'Conteúdo do módulo: Tipos de Dados.', 3, 1);
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 1: O que define melhor os conceitos de Tipos de Dados?', 0, 3);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (7, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (7, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (7, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (7, 'Serve para ignorar erros');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 2: O que define melhor os conceitos de Tipos de Dados?', 0, 3);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (8, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (8, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (8, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (8, 'Serve para ignorar erros');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 3: O que define melhor os conceitos de Tipos de Dados?', 0, 3);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (9, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (9, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (9, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (9, 'Serve para ignorar erros');
INSERT INTO tb_lessons (title, theory_content, list_order, section_id) VALUES ('Condicionais', 'Conteúdo do módulo: Condicionais.', 4, 1);
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 1: O que define melhor os conceitos de Condicionais?', 0, 4);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (10, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (10, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (10, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (10, 'Serve para ignorar erros');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 2: O que define melhor os conceitos de Condicionais?', 0, 4);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (11, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (11, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (11, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (11, 'Serve para ignorar erros');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 3: O que define melhor os conceitos de Condicionais?', 0, 4);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (12, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (12, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (12, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (12, 'Serve para ignorar erros');
INSERT INTO tb_lessons (title, theory_content, list_order, section_id) VALUES ('Laços', 'Conteúdo do módulo: Laços.', 5, 1);
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 1: O que define melhor os conceitos de Laços?', 0, 5);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (13, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (13, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (13, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (13, 'Serve para ignorar erros');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 2: O que define melhor os conceitos de Laços?', 0, 5);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (14, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (14, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (14, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (14, 'Serve para ignorar erros');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 3: O que define melhor os conceitos de Laços?', 0, 5);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (15, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (15, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (15, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (15, 'Serve para ignorar erros');
INSERT INTO tb_lessons (title, theory_content, list_order, section_id) VALUES ('Funções', 'Conteúdo do módulo: Funções.', 6, 1);
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 1: O que define melhor os conceitos de Funções?', 0, 6);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (16, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (16, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (16, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (16, 'Serve para ignorar erros');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 2: O que define melhor os conceitos de Funções?', 0, 6);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (17, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (17, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (17, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (17, 'Serve para ignorar erros');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 3: O que define melhor os conceitos de Funções?', 0, 6);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (18, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (18, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (18, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (18, 'Serve para ignorar erros');
INSERT INTO tb_lessons (title, theory_content, list_order, section_id) VALUES ('Arrays', 'Conteúdo do módulo: Arrays.', 7, 1);
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 1: O que define melhor os conceitos de Arrays?', 0, 7);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (19, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (19, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (19, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (19, 'Serve para ignorar erros');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 2: O que define melhor os conceitos de Arrays?', 0, 7);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (20, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (20, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (20, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (20, 'Serve para ignorar erros');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 3: O que define melhor os conceitos de Arrays?', 0, 7);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (21, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (21, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (21, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (21, 'Serve para ignorar erros');
INSERT INTO tb_lessons (title, theory_content, list_order, section_id) VALUES ('Objetos', 'Conteúdo do módulo: Objetos.', 8, 1);
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 1: O que define melhor os conceitos de Objetos?', 0, 8);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (22, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (22, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (22, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (22, 'Serve para ignorar erros');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 2: O que define melhor os conceitos de Objetos?', 0, 8);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (23, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (23, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (23, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (23, 'Serve para ignorar erros');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 3: O que define melhor os conceitos de Objetos?', 0, 8);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (24, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (24, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (24, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (24, 'Serve para ignorar erros');
INSERT INTO tb_lessons (title, theory_content, list_order, section_id) VALUES ('Eventos', 'Conteúdo do módulo: Eventos.', 9, 1);
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 1: O que define melhor os conceitos de Eventos?', 0, 9);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (25, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (25, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (25, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (25, 'Serve para ignorar erros');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 2: O que define melhor os conceitos de Eventos?', 0, 9);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (26, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (26, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (26, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (26, 'Serve para ignorar erros');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 3: O que define melhor os conceitos de Eventos?', 0, 9);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (27, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (27, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (27, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (27, 'Serve para ignorar erros');
INSERT INTO tb_lessons (title, theory_content, list_order, section_id) VALUES ('Projeto', 'Conteúdo do módulo: Projeto.', 10, 1);
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 1: O que define melhor os conceitos de Projeto?', 0, 10);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (28, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (28, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (28, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (28, 'Serve para ignorar erros');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 2: O que define melhor os conceitos de Projeto?', 0, 10);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (29, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (29, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (29, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (29, 'Serve para ignorar erros');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 3: O que define melhor os conceitos de Projeto?', 0, 10);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (30, 'É um recurso fundamental para programação (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (30, 'É utilizado apenas na renderização 3D');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (30, 'Não interfere no código');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (30, 'Serve para ignorar erros');

INSERT INTO tb_lessons (title, theory_content, list_order, section_id) VALUES ('HTML Básico', 'Conteúdo do módulo: HTML Básico.', 1, 2);
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 1: Como se aplica HTML Básico na web?', 1, 11);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (31, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (31, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (31, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (31, 'Configurando pacotes do sistema SO');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 2: Como se aplica HTML Básico na web?', 1, 11);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (32, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (32, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (32, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (32, 'Configurando pacotes do sistema SO');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 3: Como se aplica HTML Básico na web?', 1, 11);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (33, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (33, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (33, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (33, 'Configurando pacotes do sistema SO');
INSERT INTO tb_lessons (title, theory_content, list_order, section_id) VALUES ('Tags Textuais', 'Conteúdo do módulo: Tags Textuais.', 2, 2);
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 1: Como se aplica Tags Textuais na web?', 1, 12);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (34, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (34, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (34, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (34, 'Configurando pacotes do sistema SO');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 2: Como se aplica Tags Textuais na web?', 1, 12);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (35, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (35, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (35, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (35, 'Configurando pacotes do sistema SO');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 3: Como se aplica Tags Textuais na web?', 1, 12);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (36, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (36, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (36, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (36, 'Configurando pacotes do sistema SO');
INSERT INTO tb_lessons (title, theory_content, list_order, section_id) VALUES ('Estruturação', 'Conteúdo do módulo: Estruturação.', 3, 2);
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 1: Como se aplica Estruturação na web?', 1, 13);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (37, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (37, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (37, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (37, 'Configurando pacotes do sistema SO');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 2: Como se aplica Estruturação na web?', 1, 13);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (38, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (38, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (38, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (38, 'Configurando pacotes do sistema SO');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 3: Como se aplica Estruturação na web?', 1, 13);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (39, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (39, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (39, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (39, 'Configurando pacotes do sistema SO');
INSERT INTO tb_lessons (title, theory_content, list_order, section_id) VALUES ('CSS Básico', 'Conteúdo do módulo: CSS Básico.', 4, 2);
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 1: Como se aplica CSS Básico na web?', 1, 14);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (40, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (40, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (40, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (40, 'Configurando pacotes do sistema SO');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 2: Como se aplica CSS Básico na web?', 1, 14);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (41, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (41, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (41, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (41, 'Configurando pacotes do sistema SO');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 3: Como se aplica CSS Básico na web?', 1, 14);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (42, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (42, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (42, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (42, 'Configurando pacotes do sistema SO');
INSERT INTO tb_lessons (title, theory_content, list_order, section_id) VALUES ('Box Model', 'Conteúdo do módulo: Box Model.', 5, 2);
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 1: Como se aplica Box Model na web?', 1, 15);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (43, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (43, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (43, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (43, 'Configurando pacotes do sistema SO');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 2: Como se aplica Box Model na web?', 1, 15);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (44, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (44, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (44, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (44, 'Configurando pacotes do sistema SO');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 3: Como se aplica Box Model na web?', 1, 15);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (45, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (45, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (45, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (45, 'Configurando pacotes do sistema SO');
INSERT INTO tb_lessons (title, theory_content, list_order, section_id) VALUES ('Flexbox', 'Conteúdo do módulo: Flexbox.', 6, 2);
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 1: Como se aplica Flexbox na web?', 1, 16);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (46, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (46, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (46, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (46, 'Configurando pacotes do sistema SO');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 2: Como se aplica Flexbox na web?', 1, 16);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (47, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (47, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (47, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (47, 'Configurando pacotes do sistema SO');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 3: Como se aplica Flexbox na web?', 1, 16);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (48, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (48, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (48, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (48, 'Configurando pacotes do sistema SO');
INSERT INTO tb_lessons (title, theory_content, list_order, section_id) VALUES ('Grid', 'Conteúdo do módulo: Grid.', 7, 2);
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 1: Como se aplica Grid na web?', 1, 17);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (49, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (49, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (49, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (49, 'Configurando pacotes do sistema SO');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 2: Como se aplica Grid na web?', 1, 17);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (50, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (50, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (50, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (50, 'Configurando pacotes do sistema SO');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 3: Como se aplica Grid na web?', 1, 17);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (51, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (51, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (51, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (51, 'Configurando pacotes do sistema SO');
INSERT INTO tb_lessons (title, theory_content, list_order, section_id) VALUES ('JS na Web', 'Conteúdo do módulo: JS na Web.', 8, 2);
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 1: Como se aplica JS na Web na web?', 1, 18);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (52, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (52, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (52, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (52, 'Configurando pacotes do sistema SO');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 2: Como se aplica JS na Web na web?', 1, 18);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (53, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (53, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (53, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (53, 'Configurando pacotes do sistema SO');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 3: Como se aplica JS na Web na web?', 1, 18);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (54, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (54, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (54, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (54, 'Configurando pacotes do sistema SO');
INSERT INTO tb_lessons (title, theory_content, list_order, section_id) VALUES ('Manipulação DOM', 'Conteúdo do módulo: Manipulação DOM.', 9, 2);
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 1: Como se aplica Manipulação DOM na web?', 1, 19);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (55, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (55, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (55, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (55, 'Configurando pacotes do sistema SO');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 2: Como se aplica Manipulação DOM na web?', 1, 19);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (56, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (56, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (56, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (56, 'Configurando pacotes do sistema SO');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 3: Como se aplica Manipulação DOM na web?', 1, 19);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (57, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (57, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (57, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (57, 'Configurando pacotes do sistema SO');
INSERT INTO tb_lessons (title, theory_content, list_order, section_id) VALUES ('Projeto Final', 'Conteúdo do módulo: Projeto Final.', 10, 2);
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 1: Como se aplica Projeto Final na web?', 1, 20);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (58, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (58, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (58, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (58, 'Configurando pacotes do sistema SO');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 2: Como se aplica Projeto Final na web?', 1, 20);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (59, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (59, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (59, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (59, 'Configurando pacotes do sistema SO');
INSERT INTO tb_exercises (question, correct_answer, lesson_id) VALUES ('Aula 3: Como se aplica Projeto Final na web?', 1, 20);
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (60, 'Através de ferramentas backend fechadas');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (60, 'Construindo o layout e comportamento no navegador (Correta)');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (60, 'Rodando queries no banco de dados');
INSERT INTO tb_exercises_options (exercise_id, options) VALUES (60, 'Configurando pacotes do sistema SO');