INSERT INTO tb_kanban_templates (title, description, priority, lesson_id) VALUES ('Praticar: Introdução', 'Complete os exercícios e práticas sobre Introdução.', 'Média', 1);
INSERT INTO tb_kanban_templates (title, description, priority, lesson_id) VALUES ('Praticar: Variáveis', 'Complete os exercícios e práticas sobre Variáveis.', 'Média', 2);
INSERT INTO tb_kanban_templates (title, description, priority, lesson_id) VALUES ('Praticar: Tipos de Dados', 'Complete os exercícios e práticas sobre Tipos de Dados.', 'Média', 3);
INSERT INTO tb_kanban_templates (title, description, priority, lesson_id) VALUES ('Praticar: Condicionais', 'Complete os exercícios e práticas sobre Condicionais.', 'Média', 4);
INSERT INTO tb_kanban_templates (title, description, priority, lesson_id) VALUES ('Praticar: Laços', 'Complete os exercícios e práticas sobre Laços.', 'Média', 5);
INSERT INTO tb_kanban_templates (title, description, priority, lesson_id) VALUES ('Praticar: Funções', 'Complete os exercícios e práticas sobre Funções.', 'Média', 6);
INSERT INTO tb_kanban_templates (title, description, priority, lesson_id) VALUES ('Praticar: Arrays', 'Complete os exercícios e práticas sobre Arrays.', 'Média', 7);
INSERT INTO tb_kanban_templates (title, description, priority, lesson_id) VALUES ('Praticar: Objetos', 'Complete os exercícios e práticas sobre Objetos.', 'Média', 8);
INSERT INTO tb_kanban_templates (title, description, priority, lesson_id) VALUES ('Praticar: Eventos', 'Complete os exercícios e práticas sobre Eventos.', 'Média', 9);
INSERT INTO tb_kanban_templates (title, description, priority, lesson_id) VALUES ('Praticar: Projeto', 'Complete os exercícios e práticas sobre Projeto.', 'Média', 10);
INSERT INTO tb_kanban_templates (title, description, priority, lesson_id) VALUES ('Desenvolver: HTML Básico', 'Projete layouts básicos utilizando HTML Básico.', 'Alta', 11);
INSERT INTO tb_kanban_templates (title, description, priority, lesson_id) VALUES ('Desenvolver: Tags Textuais', 'Projete layouts básicos utilizando Tags Textuais.', 'Alta', 12);
INSERT INTO tb_kanban_templates (title, description, priority, lesson_id) VALUES ('Desenvolver: Estruturação', 'Projete layouts básicos utilizando Estruturação.', 'Alta', 13);
INSERT INTO tb_kanban_templates (title, description, priority, lesson_id) VALUES ('Desenvolver: CSS Básico', 'Projete layouts básicos utilizando CSS Básico.', 'Alta', 14);
INSERT INTO tb_kanban_templates (title, description, priority, lesson_id) VALUES ('Desenvolver: Box Model', 'Projete layouts básicos utilizando Box Model.', 'Alta', 15);
INSERT INTO tb_kanban_templates (title, description, priority, lesson_id) VALUES ('Desenvolver: Flexbox', 'Projete layouts básicos utilizando Flexbox.', 'Alta', 16);
INSERT INTO tb_kanban_templates (title, description, priority, lesson_id) VALUES ('Desenvolver: Grid', 'Projete layouts básicos utilizando Grid.', 'Alta', 17);
INSERT INTO tb_kanban_templates (title, description, priority, lesson_id) VALUES ('Desenvolver: JS na Web', 'Projete layouts básicos utilizando JS na Web.', 'Alta', 18);
INSERT INTO tb_kanban_templates (title, description, priority, lesson_id) VALUES ('Desenvolver: Manipulação DOM', 'Projete layouts básicos utilizando Manipulação DOM.', 'Alta', 19);
INSERT INTO tb_kanban_templates (title, description, priority, lesson_id) VALUES ('Desenvolver: Projeto Final', 'Projete layouts básicos utilizando Projeto Final.', 'Alta', 20);